# Generated by Django 5.2.7 on 2025-11-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="submitted_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
