# Generated by Django 5.2.7 on 2025-10-28 17:44

from django.db import migrations

import apps.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_is_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.authentication.models.UserManager()),
            ],
        ),
    ]
