# Generated by Django 5.1.4 on 2025-10-09 20:44

from django.db import migrations


def verify_existing_users(apps, schema_editor):
    """
    Mark all existing users as email verified.

    This migration runs after adding the is_email_verified field.
    Since we're adding email verification as a new feature, we want to
    grandfather in existing users who already have accounts.
    """
    User = apps.get_model("authentication", "User")
    User.objects.all().update(is_email_verified=True)


def reverse_verify_existing_users(apps, schema_editor):
    """
    Reverse operation - mark all users as unverified.
    This is just for migration reversibility, rarely used in practice.
    """
    User = apps.get_model("authentication", "User")
    User.objects.all().update(is_email_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_is_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.RunPython(verify_existing_users, reverse_verify_existing_users),
    ]
