# Generated by Django 5.2.7 on 2025-10-28 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "size_sqft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Plot size in square feet",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("grass_type", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plots_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("water", "Water"),
                            ("fertilizer", "Fertilizer"),
                            ("chemical", "Chemical"),
                            ("mowing", "Mowing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="turf_research.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="MowingTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "height_inches",
                    models.DecimalField(
                        decimal_places=2, help_text="Mowing height in inches", max_digits=4
                    ),
                ),
                ("clippings_removed", models.BooleanField(default=False)),
                (
                    "mower_type",
                    models.CharField(blank=True, help_text="Type of mower used", max_length=50),
                ),
                (
                    "pattern",
                    models.CharField(
                        blank=True, help_text="Mowing pattern or direction", max_length=50
                    ),
                ),
                (
                    "treatment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mowing_details",
                        to="turf_research.treatment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FertilizerTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                (
                    "npk_ratio",
                    models.CharField(
                        blank=True, help_text="N-P-K ratio (e.g., 20-10-10)", max_length=20
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount applied", max_digits=10
                    ),
                ),
                (
                    "amount_unit",
                    models.CharField(
                        default="lbs", help_text="Unit (e.g., lbs, oz, kg)", max_length=20
                    ),
                ),
                (
                    "rate_per_1000sqft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Application rate per 1000 sq ft",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "treatment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fertilizer_details",
                        to="turf_research.treatment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChemicalTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chemical_type",
                    models.CharField(
                        choices=[
                            ("herbicide", "Herbicide"),
                            ("insecticide", "Insecticide"),
                            ("fungicide", "Fungicide"),
                            ("growth_regulator", "Growth Regulator"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("active_ingredient", models.CharField(blank=True, max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount applied", max_digits=10
                    ),
                ),
                (
                    "amount_unit",
                    models.CharField(
                        default="oz", help_text="Unit (e.g., oz, lbs, ml, gal)", max_length=20
                    ),
                ),
                (
                    "rate_per_1000sqft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Application rate per 1000 sq ft",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("target_pest", models.CharField(blank=True, max_length=200)),
                (
                    "treatment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemical_details",
                        to="turf_research.treatment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount_inches",
                    models.DecimalField(
                        decimal_places=2, help_text="Water amount in inches", max_digits=5
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(blank=True, help_text="Duration in minutes", null=True),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="Irrigation method (e.g., sprinkler, drip)",
                        max_length=50,
                    ),
                ),
                (
                    "treatment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_details",
                        to="turf_research.treatment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(fields=["plot", "date"], name="turf_resear_plot_id_4e0d58_idx"),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["treatment_type", "date"], name="turf_resear_treatme_b7228c_idx"
            ),
        ),
    ]
