# Generated by Django 5.2.7 on 2025-10-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turf_research", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="treatment",
            name="turf_resear_plot_id_4e0d58_idx",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="plot",
        ),
        migrations.AddField(
            model_name="plot",
            name="center_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Center latitude for map display",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="center_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Center longitude for map display",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="polygon_coordinates",
            field=models.JSONField(
                blank=True, help_text="GeoJSON polygon coordinates for map display", null=True
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="plots",
            field=models.ManyToManyField(
                help_text="Plots this treatment was applied to",
                related_name="treatments",
                to="turf_research.plot",
            ),
        ),
    ]
