# Generated by Django 5.2.7 on 2025-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turf_research", "0002_remove_treatment_turf_resear_plot_id_4e0d58_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="center_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Center latitude for map display",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="center_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Center longitude for map display",
                max_digits=11,
                null=True,
            ),
        ),
    ]
