# Generated by Django 5.2.7 on 2025-10-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turf_research", "0003_alter_plot_center_lat_alter_plot_center_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="parent_plot",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent plot if this is a sub-plot",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subplots",
                to="turf_research.plot",
            ),
        ),
    ]
