# Generated by Django 5.2.7 on 2025-10-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turf_research", "0004_plot_parent_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="center_lat",
            field=models.FloatField(
                blank=True, help_text="Center latitude for map display", null=True
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="center_lng",
            field=models.FloatField(
                blank=True, help_text="Center longitude for map display", null=True
            ),
        ),
    ]
