# Generated by Django 5.2.7 on 2025-10-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turf_research", "0007_alter_plot_center_lat_alter_plot_center_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="center_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Center latitude for map display",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="center_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Center longitude for map display",
                max_digits=10,
                null=True,
            ),
        ),
    ]
